name: Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm install

    - run: pwd

    - name: Zip
      run: cd dist/apps && ../../scripts/zip-apps.${{ github.sha }}.zip
