name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull Main Branch
      run: git fetch origin main

    - name: Install Deps
      run: npm install

    - name: Build
      run: npm run build:ci

    - name: Zip
      run: cd dist/apps && ../../scripts/zip-apps.${{ github.sha }}.zip
